@startuml
package "Entity" {
    class User {
        id : int
        name : string
        firstname : string
        lastname : string
        email : string
        password : string
        plainPassword : string
        registeredAt : DateTimeInterface
    }
    class Article {
        id : int
        title : string
        content : text
        image : ?file
        published : bool
        createdAt : DateTimeInterface
        updatedAt : DateTimeInterface
    }
    class Category {
        id : int
        name : string
    }
    class Tag {
        id : int
        name : string
    }
    class Client {
        id : int
        company : string
        description : text
        sector : string
        image : file
    }
    class Project {
        id : int
        name : string
        url :string
        description : text
        date : DateTimeInterface
    }
    class Image {
        id : int
        name : string
        path : string
        url : string
        type : string
    }
    class Techno {
        id : int
        name : string
        type : string
    }
    class Education {
        id : int
        title : string
        institution : string
        description : text
        country : string
        year : int
        sector : int
        image : ?file
    }
    class Skill {
        id : int
        name : string
        level : int
    }

    User --{ Education
    User --{ Skill
    User --{ Techno

    Article }-- User
    Article }-- Category
    Article }--{ Tag

    Client --{ Project
    Project --{ Techno
    Image }-- Project
}
@enduml